name: Update README

on:
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Run script to update README
              run: python .github/scripts/script.py

            - name: Commit and push changes
              uses: actions/checkout@v4
              run: |
                  git config user.name "yoezequiel"
                  git config user.email "ezequielcasiano15@gmail.com"
                  git add README.md
                  git commit -m "Update README with latest poetry"
                  git push
