name: Update README

on:
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run script to update README
              run: python .github/scripts/script.py

            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add README.md
                  git commit -m "Update README with latest poetry"
                  git push
