name: Update README

on:
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run script to update README
              run: python .github/scripts/script.py

            - name: Commit and push changes
              run: |
                  git config --global user.name 'GitHub Actions'
                  git config --global user.email 'actions@users.noreply.github.com'
                  git add README.md
                  git commit -m "Update README with latest poetry"
                  git push
